
package net.yandex.speller.services.spellservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpellServiceSoap", targetNamespace = "http://speller.yandex.net/services/spellservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpellServiceSoap {


    /**
     * 
     * @param parameters
     * @return
     *     returns net.yandex.speller.services.spellservice.CheckTextResponse
     */
    @WebMethod(action = "http://speller.yandex.net/services/spellservice/checkText")
    @WebResult(name = "CheckTextResponse", targetNamespace = "http://speller.yandex.net/services/spellservice", partName = "parameters")
    public CheckTextResponse checkText(
        @WebParam(name = "CheckTextRequest", targetNamespace = "http://speller.yandex.net/services/spellservice", partName = "parameters")
        CheckTextRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns net.yandex.speller.services.spellservice.CheckTextsResponse
     */
    @WebMethod(action = "http://speller.yandex.net/services/spellservice/checkTexts")
    @WebResult(name = "CheckTextsResponse", targetNamespace = "http://speller.yandex.net/services/spellservice", partName = "parameters")
    public CheckTextsResponse checkTexts(
        @WebParam(name = "CheckTextsRequest", targetNamespace = "http://speller.yandex.net/services/spellservice", partName = "parameters")
        CheckTextsRequest parameters);

}
