
package io.delivery.by.belavia.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OnlineTimeTableSoap", targetNamespace = "http://webservices.belavia.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnlineTimeTableSoap {


    /**
     * <h4>���������� ������ ������ � ����������� � ������ / ������ � ��������� �����.</h4>������� ���������:<ul><li>Airport � IATA ��� ���������, ������ �� ������ ��������� ����������</li><li>Type � ��� ���������� ��� ������, ����� ��������� �������� Arrival ����������� ������� �� ���������� ���������, Departure - ���������� ������� � ��������� ��������.</li><li>ViewDate � ���� � ������� (YYYY-MM-DD), �� ������� ����� ������������ ����������, ����� ��������� �������� +/- 2 ��� �� ������� ����.</li></ul><br />������������ ������, ��������� �� ��������� �����:<ul><li>FlightNumber � ����� �����</li><li>Airport � IATA ��� ���������</li><li>ScheduleTime � ��������������� ��������� ����� ������ / ������ �����, � ������� (YYYY-MM-DDThh:mm:ss)</li><li>ExpectedTime � �������������� ��������� ����� ������ / ������ �����, � ������� (YYYY-MM-DDThh:mm:ss)</li><li>ActualTime � ����������� ��������� ����� ������ / ������ �����, � ������� (YYYY-MM-DDThh:mm:ss)</li><li>Status � ������ �����, �������� ��������� �����������:<ul><li>Arrived - ������</li><li>Canceled - ������</li><li>Delayed � ��������</li><li>Departure � �������</li><li>Scheduled � ������������</li></ul></li><li>Aircraft � ��� ���������� �����, �� ������� ����������� ����</li></ul><br /><strong>�����������: </strong>� ������ ������ ��������:  ExpectedTime, ActualTime ����� ��������� �������� ������� � ���� ������ 0001-01-01T00:00:00. ��� ������� � ���, ��� ����� �� ��������.<br /><ul><li>ExpectedTime � ����� ��������� �������� �� ������ 0001-01-01T00:00:00 ������ � ��� ������ ���� ���� ����� ������:  ��������, ������, �������, ��� ������, � ����� ���� ����� ���������������� ����� ������� �� �������� ������������.</li><li>ActualTime � ����� ��������� �������� �� ������ 0001-01-01T00:00:00 ������ � ��� ������ ���� ������ ����� �����: ������ (���� ��� ���������� ��� ������ ����� Arrival) ��� ������� (���� ��� ���������� ��� ������ ����� Departure, � ������� ��� �� ������ � �������� ����� ��������)</li></ul>
     * 
     * @param type
     * @param viewDate
     * @param airport
     * @return
     *     returns TimeTableResponce
     */
    @WebMethod(operationName = "GetTimeTable", action = "http://webservices.belavia.by/GetTimeTable")
    @WebResult(name = "GetTimeTableResult", targetNamespace = "http://webservices.belavia.by/")
    @RequestWrapper(localName = "GetTimeTable", targetNamespace = "http://webservices.belavia.by/", className = "GetTimeTable")
    @ResponseWrapper(localName = "GetTimeTableResponse", targetNamespace = "http://webservices.belavia.by/", className = "GetTimeTableResponse")
    public TimeTableResponce getTimeTable(
        @WebParam(name = "Airport", targetNamespace = "http://webservices.belavia.by/")
        String airport,
        @WebParam(name = "Type", targetNamespace = "http://webservices.belavia.by/")
        TimeTableType type,
        @WebParam(name = "ViewDate", targetNamespace = "http://webservices.belavia.by/")
        XMLGregorianCalendar viewDate);

    /**
     * <h4>���������� ������ ����������, ��� ���� ���������� � ����������� ������.</h4>������� ���������:<ul><li>Language - ������ ��, ����� ����� ������ ����� �������� ������. �� ������ ������ ���������� �������� ��������� �EN�, �RU�. ������� ����������� ���������� �� �����</li></ul><br />������������ ������, ��������� �� ��������� �����:<ul><li>IATA -  ��� IATA, ���������</li><li>Name � ��������, ��������� �� ��������� � ������� �����</li></ul><br /><strong>�����������: </strong>������ ���������� �������� �������������� ������� Name, �� ���� ���� �������� ��������� �� �������� ��������, ����� ������ �������� ���������, �� �����.
     * 
     * @param language
     * @return
     *     returns AirportsResponse
     */
    @WebMethod(operationName = "GetAirportsList", action = "http://webservices.belavia.by/GetAirportsList")
    @WebResult(name = "GetAirportsListResult", targetNamespace = "http://webservices.belavia.by/")
    @RequestWrapper(localName = "GetAirportsList", targetNamespace = "http://webservices.belavia.by/", className = "GetAirportsList")
    @ResponseWrapper(localName = "GetAirportsListResponse", targetNamespace = "http://webservices.belavia.by/", className = "GetAirportsListResponse")
    public AirportsResponse getAirportsList(
        @WebParam(name = "Language", targetNamespace = "http://webservices.belavia.by/")
        String language);

}
