
package io.delivery.com.cdyne.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LuhnCheckerSoap", targetNamespace = "http://ws.cdyne.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LuhnCheckerSoap {


    /**
     * Enter 4111111111111111 to test a good credit card number.
     * 
     * @param cardNumber
     * @return
     *     returns ReturnIndicator
     */
//    @WebMethod(operationName = "CheckCC", action = "http://ws.cdyne.com/CheckCC")
//    @WebResult(name = "CheckCCResult", targetNamespace = "http://ws.cdyne.com/")
//    @RequestWrapper(localName = "CheckCC", targetNamespace = "http://ws.cdyne.com/", className = "CheckCC")
//    @ResponseWrapper(localName = "CheckCCResponse", targetNamespace = "http://ws.cdyne.com/", className = "CheckCCResponse")
//    public ReturnIndicator checkCC(
//        @WebParam(name = "CardNumber", targetNamespace = "http://ws.cdyne.com/")
//        String cardNumber);

    @WebMethod(operationName = "CheckCC", action = "http://ws.cdyne.com/CheckCC")
    @WebResult(name = "CheckCCResult", targetNamespace = "http://ws.cdyne.com/")
    @RequestWrapper(localName = "CheckCC", targetNamespace = "http://ws.cdyne.com/", className = "CheckCC")
    @ResponseWrapper(localName = "CheckCCResponse", targetNamespace = "http://ws.cdyne.com/", className = "CheckCCResponse")
    public ReturnIndicator returnIndicator(
            @WebParam(name = "CardNumber", targetNamespace = "http://ws.cdyne.com/")
                    String cardNumber);

}
