
package t320.nks34;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServicePortType", targetNamespace = "http://nks34.t320")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServicePortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:helloName")
    @WebResult(targetNamespace = "http://nks34.t320")
    @RequestWrapper(localName = "helloName", targetNamespace = "http://nks34.t320", className = "t320.nks34.HelloName")
    @ResponseWrapper(localName = "helloNameResponse", targetNamespace = "http://nks34.t320", className = "t320.nks34.HelloNameResponse")
    public String helloName(
        @WebParam(name = "name", targetNamespace = "http://nks34.t320")
        String name);

}
